version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client
    ports:
      - '3000:3000'
